# Generated by Django 2.0.9 on 2021-11-13 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=64, verbose_name='基金名称')),
                ('code', models.CharField(db_index=True, max_length=64, verbose_name='代码')),
            ],
        ),
    ]
