# Generated by Django 6.0.1 on 2026-04-15 04:34

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.IntegerField(
                    choices=[(1, '医疗'), (2, '白酒'), (3, '半导体'), (4, '军工'), (6, '黄金'), (7, '债券')],
                    default=0)),
                ('name', models.CharField(db_index=True, max_length=64, verbose_name='基金名称')),
                ('code', models.CharField(db_index=True, max_length=64, verbose_name='代码')),
                ('fee', models.FloatField(default=0, verbose_name='买入费率 %')),
                ('newest_rate', models.FloatField(default=0, null=True, verbose_name='最新估算涨幅')),
                ('high_sale_low_buy', models.BooleanField(default=False, verbose_name='高抛低吸')),
                ('is_advance', models.BooleanField(default=True, verbose_name='是否是进阶理财')),
                ('sell_percentage', models.FloatField(default=0, verbose_name='涨幅到出售')),
                ('buy_percentage', models.FloatField(default=0, verbose_name='涨幅到购买')),
            ],
            options={
                'verbose_name_plural': '基金',
            },
        ),
        migrations.CreateModel(
            name='FundHoldings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catetory_name', models.CharField(max_length=64, verbose_name='分类')),
                ('expense', models.FloatField(default=0, verbose_name='确认金额')),
                ('hold', models.FloatField(default=0, verbose_name='持有份额')),
            ],
            options={
                'verbose_name_plural': '基金仓位',
            },
        ),
        migrations.CreateModel(
            name='FundExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deal_at', models.DateField(db_index=True, verbose_name='交易日期')),
                ('expense', models.FloatField(default=0, verbose_name='确认金额')),
                ('hold', models.FloatField(default=0, verbose_name='确认份额')),
                ('hold_rate', models.FloatField(default=0, verbose_name='持有收益率')),
                ('expense_type', models.CharField(default='buy', max_length=8, verbose_name='基金交易类型: buy: 购买；sale：出售')),
                ('split_hold', models.FloatField(default=0, verbose_name='拆分份额')),
                ('sale_at', models.DateField(blank=True, default=None, null=True, verbose_name='出售日期')),
                ('need_buy_again', models.BooleanField(default=False, verbose_name='卖出去过的')),
                ('newest_value', models.FloatField(default=0, verbose_name='最新单位净值')),
                ('annual_interest_rate',
                 models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='投资回报年化率%')),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fund.fund',
                                           verbose_name='基金名称')),
            ],
            options={
                'verbose_name_plural': '基金购买记录',
            },
        ),
        migrations.CreateModel(
            name='FundValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deal_at', models.DateField(db_index=True, verbose_name='发布日期')),
                ('value', models.FloatField(verbose_name='单位净值')),
                ('rate', models.FloatField(default=0, verbose_name='日增长率')),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fund.fund',
                                           verbose_name='基金名称')),
            ],
            options={
                'verbose_name_plural': '基金净值',
                'unique_together': {('fund', 'deal_at')},
            },
        ),
    ]
