# Generated by Django 3.2.9 on 2022-01-10 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=64, verbose_name='基金名称')),
                ('code', models.CharField(db_index=True, max_length=64, verbose_name='代码')),
                ('three_yearly_change', models.IntegerField(default=0, verbose_name='三年年化')),
                ('space_expense', models.IntegerField(default=0, verbose_name='单份投入金额')),
                ('from_value', models.FloatField(default=0, verbose_name='从该单位净值开始')),
                ('to_value', models.FloatField(default=0, verbose_name='到该单位净值结束')),
                ('fee', models.FloatField(default=0, verbose_name='买入费率 %')),
                ('newest_rate', models.FloatField(default=0, null=True, verbose_name='最新估算涨幅')),
                ('transaction_rule', models.CharField(default='', max_length=64, verbose_name='交易规则')),
                ('high_sale_low_buy', models.BooleanField(default=False, verbose_name='高抛低吸')),
                ('best_transaction_rule_days', models.IntegerField(default=30, verbose_name='最优出售天数')),
            ],
            options={
                'verbose_name_plural': '基金',
            },
        ),
        migrations.CreateModel(
            name='FundHoldings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catetory_name', models.CharField(max_length=64, verbose_name='分类')),
                ('expense', models.FloatField(default=0, verbose_name='确认金额')),
            ],
            options={
                'verbose_name_plural': '基金仓位',
            },
        ),
        migrations.CreateModel(
            name='FundExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deal_at', models.DateField(db_index=True, verbose_name='交易日期')),
                ('expense', models.FloatField(default=0, verbose_name='确认金额')),
                ('hold', models.FloatField(default=0, verbose_name='确认份额')),
                ('hold_rate', models.FloatField(default=0, verbose_name='持有收益率')),
                ('sale_using_date', models.DateField(blank=True, default=None, null=True, verbose_name='可售恢复时间')),
                ('expense_type', models.CharField(default='buy', max_length=8, verbose_name='基金交易类型: buy: 购买；sale：出售')),
                ('split_hold', models.FloatField(default=0, verbose_name='拆分份额')),
                ('sale_at', models.DateField(blank=True, default=None, null=True, verbose_name='出售日期')),
                ('is_buy_again', models.BooleanField(default=False, verbose_name='是否已经回购')),
                ('fund',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fund.fund', verbose_name='基金名称')),
            ],
            options={
                'verbose_name_plural': '基金购买记录',
            },
        ),
        migrations.CreateModel(
            name='FundValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deal_at', models.DateField(db_index=True, verbose_name='发布日期')),
                ('value', models.FloatField(verbose_name='单位净值')),
                ('rate', models.FloatField(verbose_name='日增长率')),
                ('fund',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fund.fund', verbose_name='基金名称')),
            ],
            options={
                'verbose_name_plural': '基金净值',
                'unique_together': {('fund', 'deal_at')},
            },
        ),
    ]
