# Generated by Django 3.2.9 on 2025-02-06 05:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('fund', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fund',
            name='transaction_rule',
        ),
        migrations.AlterField(
            model_name='fund',
            name='category',
            field=models.IntegerField(choices=[(1, '医疗'), (2, '白酒'), (3, '半导体'), (4, '军工'), (5, '新能源'), (6, '黄金'), (7, '债券')], default=0),
        ),
    ]
