# Generated by Django 3.2.9 on 2022-01-11 08:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('fund', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundexpense',
            name='headimg',
            field=models.FileField(default='', upload_to='img/'),
        ),
    ]
