# Generated by Django 3.2.9 on 2022-01-17 07:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('fund', '0002_fundexpense_headimg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fundexpense',
            name='headimg',
        ),
    ]
