# Generated by Django 3.2.9 on 2025-02-06 05:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('fund', '0002_auto_20250206_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='is_advance',
            field=models.BooleanField(default=True, verbose_name='是否是进阶理财'),
        ),
    ]
