# Generated by Django 3.2.9 on 2021-11-13 14:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('fund', '0002_alter_fund_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='three_yearly_change',
            field=models.CharField(db_index=True, default='', max_length=64, verbose_name='三年年化'),
        ),
    ]
