# Generated by Django 3.2.9 on 2021-11-13 15:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('fund', '0003_fund_three_yearly_change'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund',
            name='three_yearly_change',
            field=models.IntegerField(db_index=True, default=0, max_length=64, verbose_name='三年年化'),
        ),
    ]
