# Generated by Django 3.2.9 on 2022-01-21 02:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('fund', '0003_remove_fundexpense_headimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundexpense',
            name='need_buy_again',
            field=models.BooleanField(default=False, verbose_name='是否需要回购'),
        ),
    ]
