# Generated by Django 3.2.9 on 2025-02-07 02:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('fund', '0003_fund_is_advance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fundexpense',
            name='is_buy_again',
        ),
    ]
