# Generated by Django 3.2.9 on 2025-02-07 02:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('fund', '0004_remove_fundexpense_is_buy_again'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundexpense',
            name='annual_interest_rate',
            field=models.SmallIntegerField(default=0, verbose_name='投资回报年化率'),
        ),
    ]
