# Generated by Django 3.2.9 on 2021-11-13 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('fund', '0004_alter_fund_three_yearly_change'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deal_at', models.DateTimeField(db_index=True, verbose_name='交易时间')),
                ('value', models.FloatField(db_index=True, verbose_name='单位净值')),
                ('rate', models.FloatField(db_index=True, verbose_name='日增长率')),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fund.fund')),
            ],
        ),
    ]
