# Generated by Django 3.2.9 on 2021-11-13 15:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('fund', '0005_fundvalue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundvalue',
            name='deal_at',
            field=models.DateField(db_index=True, verbose_name='交易时间'),
        ),
    ]
