# Generated by Django 3.2.9 on 2025-02-07 03:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('fund', '0005_fundexpense_annual_interest_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundexpense',
            name='annual_interest_rate',
            field=models.FloatField(default=0, verbose_name='投资回报年化率'),
        ),
    ]
