# Generated by Django 3.2.9 on 2022-03-01 02:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('fund', '0005_remove_fundexpense_sale_using_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundexpense',
            name='need_buy_again',
            field=models.BooleanField(default=False, verbose_name='卖出去过的'),
        ),
    ]
