# Generated by Django 3.2.9 on 2021-11-14 01:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('fund', '0006_alter_fundvalue_deal_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundvalue',
            name='expense',
            field=models.FloatField(default=0, verbose_name='消费金额'),
        ),
        migrations.AlterField(
            model_name='fund',
            name='three_yearly_change',
            field=models.IntegerField(default=0, verbose_name='三年年化'),
        ),
        migrations.AlterField(
            model_name='fundvalue',
            name='deal_at',
            field=models.DateField(db_index=True, verbose_name='发布日期'),
        ),
        migrations.AlterField(
            model_name='fundvalue',
            name='fund',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fund.fund', verbose_name='基金名称'),
        ),
        migrations.AlterField(
            model_name='fundvalue',
            name='rate',
            field=models.FloatField(verbose_name='日增长率'),
        ),
        migrations.AlterField(
            model_name='fundvalue',
            name='value',
            field=models.FloatField(verbose_name='单位净值'),
        ),
        migrations.AlterUniqueTogether(
            name='fundvalue',
            unique_together={('fund', 'deal_at')},
        ),
    ]
