# Generated by Django 3.2.9 on 2022-03-02 06:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('fund', '0006_alter_fundexpense_need_buy_again'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundholdings',
            name='hold',
            field=models.FloatField(default=0, verbose_name='持有份额'),
        ),
    ]
