# Generated by Django 3.2.9 on 2025-02-12 02:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('fund', '0007_alter_fundexpense_annual_interest_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fund',
            name='three_yearly_change',
        ),
        migrations.AlterField(
            model_name='fundexpense',
            name='annual_interest_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='投资回报年化率%'),
        ),
    ]
