# Generated by Django 3.2.9 on 2022-10-26 02:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('fund', '0007_fundholdings_hold'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='category',
            field=models.IntegerField(choices=[(1, '🏥'), (2, '🍶'), (3, '📻'), (4, '🎖️'), (5, '🚗')], default=0),
        ),
    ]
