# Generated by Django 3.2.9 on 2021-11-14 01:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('fund', '0007_auto_20211114_0922'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fund',
            options={'verbose_name_plural': '基金'},
        ),
        migrations.AlterModelOptions(
            name='fundvalue',
            options={'verbose_name_plural': '基金净值'},
        ),
        migrations.RemoveField(
            model_name='fundvalue',
            name='expense',
        ),
        migrations.CreateModel(
            name='FundExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense', models.FloatField(default=0, verbose_name='买入')),
                ('fund_value', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fund.fundvalue',
                                                    verbose_name='基金市值')),
            ],
            options={
                'verbose_name_plural': '基金购买记录',
            },
        ),
    ]
