# Generated by Django 3.2.9 on 2025-02-12 02:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('fund', '0008_auto_20250212_1045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fund',
            name='from_value',
        ),
        migrations.RemoveField(
            model_name='fund',
            name='space_expense',
        ),
        migrations.RemoveField(
            model_name='fund',
            name='to_value',
        ),
    ]
