# Generated by Django 3.2.9 on 2021-11-14 01:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('fund', '0008_auto_20211114_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundexpense',
            name='hold',
            field=models.FloatField(default=0, verbose_name='持有份数'),
        ),
        migrations.AlterField(
            model_name='fundexpense',
            name='expense',
            field=models.FloatField(default=0, verbose_name='确认金额'),
        ),
    ]
