# Generated by Django 3.2.9 on 2022-11-12 16:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('fund', '0008_fund_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundexpense',
            name='newest_value',
            field=models.FloatField(default=0, verbose_name='最新单位净值'),
        ),
        migrations.AlterField(
            model_name='fund',
            name='category',
            field=models.IntegerField(choices=[(1, '医疗'), (2, '白酒'), (3, '半导体'), (4, '军工'), (5, '新能源')], default=0),
        ),
    ]
