# Generated by Django 3.2.9 on 2025-02-12 02:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('fund', '0009_auto_20250212_1051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fund',
            name='best_transaction_rule_days',
        ),
    ]
