# Generated by Django 3.2.9 on 2021-11-15 00:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('fund', '0009_auto_20211114_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='space_expense',
            field=models.IntegerField(default=0, verbose_name='总仓位的55份投入金额'),
        ),
    ]
