# Generated by Django 3.2.9 on 2022-11-12 16:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('fund', '0009_auto_20221113_0013'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundexpense',
            name='hold_rate_test',
            field=models.FloatField(default=0, verbose_name='持有收益率'),
        ),
    ]
