# Generated by Django 3.2.9 on 2025-03-17 08:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('fund', '0010_remove_fund_best_transaction_rule_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundvalue',
            name='rate',
            field=models.FloatField(default=0, verbose_name='日增长率'),
        ),
    ]
