# Generated by Django 3.2.9 on 2021-11-15 00:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('fund', '0010_fund_space_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='from_value',
            field=models.IntegerField(default=0, verbose_name='目前从该市值往 to_value 走'),
        ),
        migrations.AddField(
            model_name='fund',
            name='to_value',
            field=models.IntegerField(default=0, verbose_name='目前从 from_value 市值往该市值'),
        ),
    ]
