# Generated by Django 3.2.9 on 2022-11-12 16:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('fund', '0010_fundexpense_hold_rate_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fundexpense',
            name='hold_rate_test',
        ),
    ]
