# Generated by Django 3.2.9 on 2021-11-15 00:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('fund', '0011_auto_20211115_0817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund',
            name='from_value',
            field=models.FloatField(default=0, verbose_name='从该市值开始'),
        ),
        migrations.AlterField(
            model_name='fund',
            name='to_value',
            field=models.FloatField(default=0, verbose_name='到该市值结束'),
        ),
    ]
