# Generated by Django 3.2.9 on 2025-12-02 13:05

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ('fund', '0011_alter_fundvalue_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='buy_percentage',
            field=models.FloatField(default=0, verbose_name='涨幅到购买'),
        ),
        migrations.AddField(
            model_name='fund',
            name='sell_percentage',
            field=models.FloatField(default=0, verbose_name='涨幅到出售'),
        ),
    ]
