# Generated by Django 3.2.9 on 2026-01-14 08:37

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ('fund', '0012_auto_20251202_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundexpense',
            name='gold_gram',
            field=models.FloatField(default=0, verbose_name='黄金克数'),
        ),
    ]
