# Generated by Django 3.2.9 on 2021-11-15 01:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('fund', '0013_auto_20211115_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundexpense',
            name='deal_at',
            field=models.DateField(db_index=True, verbose_name='发布日期'),
        ),
        migrations.AlterField(
            model_name='fundexpense',
            name='fund',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fund.fund', verbose_name='基金名称'),
        ),
    ]
