# Generated by Django 3.2.9 on 2026-01-14 08:49

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ('fund', '0013_fundexpense_gold_gram'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundvalue',
            name='gold_price',
            field=models.FloatField(default=0, verbose_name='成交金价'),
        ),
    ]
