# Generated by Django 3.2.9 on 2021-11-15 01:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('fund', '0014_auto_20211115_0947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fundexpense',
            name='fund_value',
        ),
    ]
