# Generated by Django 3.2.9 on 2026-01-14 08:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('fund', '0014_fundvalue_gold_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fundexpense',
            name='gold_gram',
        ),
    ]
