# Generated by Django 6.0.1 on 2026-02-25 02:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('fund', '0015_remove_fundexpense_gold_gram'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fundvalue',
            name='gold_price',
        ),
    ]
