# Generated by Django 2.0.9 on 2021-11-15 10:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('fund', '0015_remove_fundexpense_fund_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='fund',
            name='space_expense',
            field=models.IntegerField(default=0, verbose_name='单份投入金额'),
        ),
        migrations.AlterField(
            model_name='fundexpense',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='fundvalue',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
