# Generated by Django 3.2.9 on 2021-11-15 10:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('fund', '0016_auto_20211115_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='fundexpense',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='fundvalue',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
