# Generated by Django 3.2.9 on 2021-11-15 15:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('fund', '0017_auto_20211115_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='fee',
            field=models.FloatField(default=0, verbose_name='买入费率'),
        ),
        migrations.AlterField(
            model_name='fundexpense',
            name='hold',
            field=models.FloatField(default=0, verbose_name='确认份额'),
        ),
    ]
