# Generated by Django 3.2.9 on 2021-11-15 16:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('fund', '0018_auto_20211115_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund',
            name='fee',
            field=models.FloatField(default=0, verbose_name='买入费率 %'),
        ),
    ]
