# Generated by Django 3.2.9 on 2021-11-16 12:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('fund', '0019_alter_fund_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund',
            name='from_value',
            field=models.FloatField(default=0, verbose_name='从该单位净值开始'),
        ),
        migrations.AlterField(
            model_name='fund',
            name='three_yearly_change',
            field=models.FloatField(default=0, verbose_name='三年年化'),
        ),
        migrations.AlterField(
            model_name='fund',
            name='to_value',
            field=models.FloatField(default=0, verbose_name='到该单位净值结束'),
        ),
    ]
