# Generated by Django 3.2.9 on 2021-11-18 06:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('fund', '0020_auto_20211116_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='order',
            field=models.IntegerField(default=0, verbose_name='排序'),
        ),
    ]
