# Generated by Django 3.2.9 on 2021-11-19 03:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('fund', '0021_fund_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fund',
            name='order',
        ),
        migrations.AddField(
            model_name='fund',
            name='newest_rate',
            field=models.FloatField(default=0, null=True, verbose_name='最新估算涨幅'),
        ),
    ]
