# Generated by Django 3.2.9 on 2021-11-25 00:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('fund', '0022_auto_20211119_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund',
            name='three_yearly_change',
            field=models.IntegerField(default=0, verbose_name='三年年化'),
        ),
    ]
