# Generated by Django 3.2.9 on 2021-11-25 00:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('fund', '0023_alter_fund_three_yearly_change'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='transaction_rule',
            field=models.CharField(default='', max_length=64, verbose_name='交易规则'),
        ),
    ]
