# Generated by Django 3.2.9 on 2021-11-25 05:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('fund', '0024_fund_transaction_rule'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='high_sale_low_buy',
            field=models.BooleanField(default=False, verbose_name='高抛低吸'),
        ),
    ]
