# Generated by Django 3.2.9 on 2021-11-29 09:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('fund', '0025_fund_high_sale_low_buy'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundexpense',
            name='hold_rate',
            field=models.FloatField(default=0, verbose_name='持有收益率'),
        ),
    ]
