# Generated by Django 3.2.9 on 2021-12-01 06:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('fund', '0026_fundexpense_hold_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundHoldings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catetory_name', models.CharField(max_length=64, verbose_name='分类')),
                ('expense', models.FloatField(default=0, verbose_name='确认金额')),
            ],
            options={
                'verbose_name_plural': '基金仓位',
            },
        ),
    ]
