# Generated by Django 3.2.9 on 2021-12-30 15:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('fund', '0028_fundexpense_sale_using_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundexpense',
            name='expense_type',
            field=models.CharField(default='buy', max_length=8, verbose_name='基金交易类型: buy: 购买；sale：出售'),
        ),
    ]
