# Generated by Django 3.2.9 on 2021-12-30 15:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('fund', '0029_fundexpense_expense_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='best_transaction_rule_days',
            field=models.IntegerField(default=30, verbose_name='最优出售天数'),
        ),
    ]
