# Generated by Django 3.2.9 on 2021-12-31 09:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('fund', '0032_alter_fundexpense_split_hold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundexpense',
            name='split_hold',
            field=models.FloatField(default=0, verbose_name='拆分份额'),
        ),
    ]
