# Generated by Django 3.2.9 on 2022-01-04 01:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('fund', '0033_alter_fundexpense_split_hold'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundexpense',
            name='sale_at',
            field=models.DateField(default=None, null=True, verbose_name='出售日期'),
        ),
    ]
