# Generated by Django 3.2.9 on 2022-01-04 01:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('fund', '0034_fundexpense_sale_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundexpense',
            name='sale_using_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='可售恢复时间'),
        ),
    ]
