# Generated by Django 3.2.9 on 2022-01-04 13:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('fund', '0035_alter_fundexpense_sale_using_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundexpense',
            name='sale_at',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='出售日期'),
        ),
    ]
