# Generated by Django 3.2.9 on 2022-01-10 06:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('fund', '0036_alter_fundexpense_sale_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundexpense',
            name='is_buy_again',
            field=models.BooleanField(default=False, verbose_name='是否已经回购'),
        ),
    ]
