# Generated by Django 3.2.9 on 2021-11-18 17:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('douyin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='douyinuser',
            name='href',
            field=models.URLField(default='', verbose_name='链接'),
        ),
        migrations.AddField(
            model_name='douyinuser',
            name='relationship',
            field=models.CharField(default='', max_length=32, verbose_name='关系'),
        ),
    ]
