# Generated by Django 3.2.9 on 2021-11-18 17:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('douyin', '0002_auto_20211119_0129'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='douyinuser',
            options={'verbose_name_plural': '抖音用户'},
        ),
        migrations.AddField(
            model_name='douyinuser',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='创建时间'),
            preserve_default=False,
        ),
    ]
