# Generated by Django 3.2.9 on 2021-11-19 04:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('douyin', '0003_auto_20211119_0141'),
    ]

    operations = [
        migrations.AddField(
            model_name='douyinuser',
            name='follow_count',
            field=models.IntegerField(default=0, verbose_name='关注数量'),
        ),
        migrations.AlterField(
            model_name='douyinuser',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='关注时间'),
        ),
    ]
