# Generated by Django 3.2.9 on 2021-11-19 07:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('douyin', '0004_auto_20211119_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='douyinuser',
            name='head_url',
            field=models.CharField(default='', max_length=200, null=True, verbose_name='头像地址'),
        ),
    ]
