# Generated by Django 3.2.9 on 2023-02-03 09:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('cademy', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mathcademy',
            options={'verbose_name_plural': '数学'},
        ),
    ]
