# Generated by Django 3.2.9 on 2023-02-03 09:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('cademy', '0002_alter_mathcademy_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='mathcademy',
            name='host',
            field=models.CharField(default='', max_length=200, verbose_name='网站地址'),
        ),
        migrations.AddField(
            model_name='mathcademy',
            name='name',
            field=models.CharField(default='', max_length=64, verbose_name='网站名称'),
        ),
        migrations.AddField(
            model_name='mathcademy',
            name='process',
            field=models.IntegerField(choices=[(1, '未开始学习'), (2, '学习中'), (3, '学习完成')], default=1, verbose_name='进度'),
        ),
    ]
