# Generated by Django 3.2.9 on 2023-02-03 09:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('cademy', '0003_auto_20230203_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='mathcademy',
            name='remark',
            field=models.CharField(default='', max_length=200, verbose_name='描述'),
        ),
    ]
