# Generated by Django 3.2.9 on 2023-03-01 04:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('cademy', '0006_auto_20230207_1038'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cademy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=64, verbose_name='网站名称')),
                ('host', models.CharField(default='', max_length=200, verbose_name='网站地址')),
                ('process',
                 models.IntegerField(choices=[(1, '未开始学习'), (2, '学习中'), (3, '学习完成')], default=1, verbose_name='进度')),
                ('remark', models.CharField(default='', max_length=200, verbose_name='描述')),
                ('category', models.IntegerField(choices=[(1, '数学')], default=1)),
            ],
        ),
    ]
