# Generated by Django 3.2.9 on 2023-03-17 08:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('cademy', '0008_auto_20230301_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='cademy',
            name='every_day',
            field=models.BooleanField(default=False, verbose_name='每日了解'),
        ),
        migrations.AlterField(
            model_name='cademy',
            name='category',
            field=models.IntegerField(choices=[(1, '数学类'), (2, '工具类'), (3, '网络安全')], default=1, verbose_name='类别'),
        ),
    ]
