# Generated by Django 3.2.9 on 2023-03-24 06:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('cademy', '0009_auto_20230317_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cademy',
            name='category',
            field=models.IntegerField(choices=[(1, '数学类'), (2, '工具类'), (3, '网络安全'), (4, '前端')], default=1,
                                      verbose_name='类别'),
        ),
        migrations.AlterField(
            model_name='cademy',
            name='remark',
            field=models.TextField(default='', max_length=1024, verbose_name='描述'),
        ),
    ]
