# Generated by Django 3.2.9 on 2023-04-14 08:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('cademy', '0010_auto_20230324_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cademy',
            name='category',
            field=models.IntegerField(choices=[(1, '数学类'), (2, '工具类'), (3, '网络安全'), (4, '前端'), (5, '快速构建网站')],
                                      default=1, verbose_name='类别'),
        ),
        migrations.AlterField(
            model_name='cademy',
            name='remark',
            field=models.TextField(default='', max_length=2048, verbose_name='描述'),
        ),
    ]
