# Generated by Django 3.2.9 on 2022-09-27 14:08

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=1024, verbose_name='下载地址')),
                ('is_download', models.BooleanField(default=False, verbose_name='是否下载完成')),
            ],
        ),
    ]
