# Generated by Django 3.2.9 on 2022-09-27 14:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('mv', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mv',
            old_name='url',
            new_name='download_url',
        ),
        migrations.RemoveField(
            model_name='mv',
            name='is_download',
        ),
        migrations.AddField(
            model_name='mv',
            name='action',
            field=models.CharField(default='需要下载', max_length=200, verbose_name='行为'),
        ),
    ]
