# Generated by Django 3.2.9 on 2022-09-27 15:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('mv', '0002_auto_20220927_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='mv',
            name='name',
            field=models.CharField(default='', max_length=400, null=True, verbose_name='文件名字'),
        ),
    ]
